
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "total purchases for each customer in snowflake sample data"
    columns:
      - name: o_orderdate
        description: "unique identifier"
        tests:
          - unique
          - not_null

  - name: playing_with_tests
    description: "test practice"
    columns:
      - name: c_custkey
        description: "primary key for this table"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests: 
          - accepted_values: 
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
              quote: True

  - name: dates  
  - name: incremental_time

sources: 
  - name: sample 
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders 

  - name: sf
    database: snowflake_sample_data
    schema: tpch_sf100 
    tables: 
      - name: customer 

  - name: sf10
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
    tables: 
      - name: time_dim
        columns:
          - name: t_time
            tests:
              - unique
              - not_null 
      - name: date_dim
        columns: 
          - name: d_date 
            tests: 
              - unique
              - not_null






      




